<div class="newlist">
                                <div class="riqi">
                                    <div class="ri">29</div>
                                    <div class="nianyue">2021-8</div>
                                </div>
                                <div class="newtitles">
                                    <div class="newtitle"><a href="content.html">[field:title/]</a></div>
                                    <div class="miaoshu">
                                        现在就算足不出户，只要你有一台手机、电脑就能知道最新发生的事情，纵观全球。在接下来的十一国庆假期里，相信手机、电脑会成为不少小伙伴假日里的“玩具”，经常对着手机、对着电脑不仅辐射大，还不利于眼睛的健康。怎样才能减少辐射的侵害，同时又能保护眼睛呢?
                                    </div>
                                    <p class="sj-ri">发布日期：2021-9-29</p>
                                </div>
                            </div>