<div class="xinxi col-md-6 col-xs-12">
                            <div class="xinwen">
                                <div class="tu"><img src="[field:picname/]" alt=""></div>
                                <div class="wenzi">
                                    <h4>[field:title/]</h4>
                                    <span>[field:pubdate function="MyDate('m-d',@me)"/]</span>
                                    <p> [field:description function="cn_substr(@me,200)"/]....</p>
                                </div>
                            </div>
                        </div>