<?php
$z[0]=Array("pubdate","",111,154);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",211,256);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m',@me)";
$z[2]=Array("arcurl","",404,419);
$z[2][4]=array();
$z[3]=Array("title","",421,435);
$z[3][4]=array();
$z[4]=Array("description","",531,581);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,400)";
$z[5]=Array("stime","",682,696);
$z[5][4]=array();

?>