<a href="[field:arcurl/]">
                        <div class="swiper-slide">
                            <img src="[field:picname/]" alt="">
                            <h3>[field:title/]</h3>
                            <p>[field:description function="cn_substr(@me,500)"/]...</p>
                        </div>
                    </a>
                    {/dede:arclist }
                    <!-- <div class="swiper-slide">
                        <img src="{dede:global.cfg_templets_skin