<div data-sjsel="flatty">
                                    <div class="card">
                                        <a href="[field:arcurl/]">
                                            <div class="card-tu">
                                                <img class="card__picture" src="[field:picname/]" alt="">
                                            </div>
                                            <div class="card-infos">
                                                <h2 class="card__title">[field:title/]</h2>
                                                <p class="card__text">
                                                    [field:description function="cn_substr(@me,200)"/]....
                                                </p>
                                            </div>
                                        </a>
                                    </div>


                                </div>