<div class="xinxi col-md-6 col-xs-12" id="show9">
                            <div class="xinwen">
                                <div class="tu"><img src="[field:picname/]" alt=""></div>
                                <div class="wenzi">
                                    <h4>[field:title/]</h4>
                                    <span>{dede:field.description}</span>
                                    <p>{dede:field.description}</p>
                                </div>
                            </div>
                        </div>