<li class="button clockwise both">
                    {dede:type}
                    <a href="[field:typelink/]">[field:typename/]</a> {/dede:type}
                    <div class="inner"></div>
                    <ul class="erji-menu">
                        {dede:channel type ='son' }
                        <li><a href="[field:typelink/]">[field:typename/]</a></li>
                        {/dede:channel}
                    </ul>
                </li>