<div class="xinxi col-md-6 col-xs-12 " id="show11 ">
                            <a href="[field:arcurl/] " style="text-decoration: none; display: inline; ">
                                <div class="xinwen ">
                                    <div class="tu "><img src="[field:picname/] " alt=" "></div>
                                    <div class="wenzi ">
                                        <h4 style="color: black; ">[field:title/]</h4>
                                        <span>[field:pubdate function="MyDate( 'Y-m-d',@me) "/]</span>
                                        <p> [field:description function="cn_substr(@me,200) "/]....</p>
                                    </div>
                                </div>
                            </a>
                        </div>