<div class="xinxi col-md-6 col-xs-12" id="show9">
                            <div class="xinwen">
                                <div class="tu"><img src="{dede:global.cfg_templets_skin/}/images/hj02.jpg" alt=""></div>
                                <div class="wenzi">
                                    <h4>[field:title/]</h4>
                                    <span>[field:pubdate function="MyDate('m-d',@me)"/]</span>
                                    <p>{dede:field.description}</p>
                                </div>
                            </div>
                        </div>