
<field:username itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:username>

<field:phone itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>


<field:address itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:address>

<field:content itemname="意见与反馈" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
