<div class="newlist">
                                <div class="riqi">
                                    <div class="ri">29</div>
                                    <div class="nianyue">2021-8</div>
                                </div>
                                <div class="newtitles">
                                    <div class="newtitle"><a href="[field:arcurl/]">[field:title/]</a></div>
                                    <div class="miaoshu">
                                        [field:description function="cn_substr(@me,600)"/]...
                                    </div>
                                    <p class="sj-ri">发布日期：[field:pubdate function="GetDateTimeMK(@me)" /]</p>
                                </div>
                            </div>