<div class="newlist">
                        <div class="riqi">
                            <div class="ri">[field:pubdate function="MyDate('d',@me)"/]</div>
                            <div class="nianyue">[field:pubdate function="MyDate('Y-m',@me)"/]</div>
                        </div>
                        <div class="newtitles">
                            <div class="newtitle"><a href="[field:arcurl/]">[field:title/]</a></div>
                            <div class="miaoshu">
                                [field:description function="cn_substr(@me,400)"/]...
                            </div>
                            <p class="sj-ri">发布日期：[field:stime/]</p>
                        </div>
                    </div>