
                    <li class="zs col-md-6 col-sm-12">
                        <div class="grid">
                            <figure class="effect-bubba">
                                <img src="{dede:global.cfg_templets_skin/}/images/zhan01.jpg" alt="">
                                <figcaption>
                                    <h2>[field:typename/]</h2>
                                    <p>竹荫遮几琴易韵 茶烟透窗魂生香</p>
                                    <p>竹荫遮几琴易韵 茶烟透窗魂生香</p>
                                    <button><a href="[field:typelink/]">MORE</a></button>
                                </figcaption>
                            </figure>
                        </div>
                    </li>
                    