<?php
$z[0]=Array("pubdate","",170,215);
$z[0][4]=array();
$z[0][4]['function']="MyDate('Y-m',@me)";
$z[1]=Array("arcurl","",363,378);
$z[1][4]=array();
$z[2]=Array("fulltitle","",380,398);
$z[2][4]=array();
$z[3]=Array("description","",493,543);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,600)";
$z[4]=Array("pubdate","",644,691);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";

?>