<?php
$z[0]=Array("global","",198,230);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",336,363);
$z[1][4]=array();
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",365,393);
$z[2][4]=array();
$z[2][4]['name']="cfg_indexname";
$z[3]=Array("channel","\r\n                    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                    ",424,567);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[4]=Array("global","",762,794);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",981,1013);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";

?>