<?php
$z[0]=Array("global","",402,429);
$z[0][4]=array();
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("global","",480,512);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",758,785);
$z[2][4]=array();
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("global","",787,815);
$z[3][4]=array();
$z[3][4]['name']="cfg_indexname";
$z[4]=Array("channel","\r\n                <li class=\"fge\">|</li>\r\n                <li class=\"button clockwise both\"><a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <div class=\"inner\"></div>\r\n                </li>\r\n                ",909,1179);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[5]=Array("global","",1246,1271);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmsurl";

?>