<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5rKB6aaZ');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[3]=array(2,1,1,'5a6a5b+D57u/6Iy2');
$cfg_Cs[4]=array(2,1,1,'5rip54Ot57qi6Iy2');
$cfg_Cs[5]=array(2,1,1,'6Z2Z5b+D5LmM6b6Z');
$cfg_Cs[6]=array(2,1,1,'5YW75b+D6buR6Iy2');
$cfg_Cs[7]=array(0,1,1,'6Iy26aaG6LWE6K6v');
$cfg_Cs[8]=array(7,1,1,'6Iy26aaG6LWE6K6v');
$cfg_Cs[9]=array(7,1,1,'6KGM5Lia6LWE6K6v');
$cfg_Cs[10]=array(0,1,1,'5oub5ZWG5Yqg55uf');
$cfg_Cs[11]=array(7,1,1,'6Iy255qE5bi46K+G');
$cfg_Cs[12]=array(7,1,1,'6Iy25LiO5Lq655Sf');
$cfg_Cs[13]=array(10,1,1,'6Iy25Y+y6Iy26aOO');
?>